spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/backenddb
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update